### ISSUE TITLE
Figures not rendered in HTML

### ISSUE THREAD

**Issue by fab7** [cloudFPGA/Doc#1]
Hi Dionysios, any idea why the figures of the following page are not rendered?
https://cloudfpga.github.io/Doc/pages/CFSPHERE/cfdk.html#introduction

**Comment by diamantopoulos** [comment]
Hi @fab7 , yes this is because the `cFDK`'s default branch is `main` now and not `master`. Fixed in [7259c64](https://github.com/cloudFPGA/Doc/commit/7259c64dba4e74c922c7212221578a52a2cc19eb). Thanks!
